//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockTextScreen.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LockTextScreen.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部取消 的本地化字符串。
        /// </summary>
        public static string AllCancelMenuItem {
            get {
                return ResourceManager.GetString("AllCancelMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部选中 的本地化字符串。
        /// </summary>
        public static string AllSelectMenuItem {
            get {
                return ResourceManager.GetString("AllSelectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去爱应用我的应用讨论区 的本地化字符串。
        /// </summary>
        public static string AppBaraiyingyong {
            get {
                return ResourceManager.GetString("AppBaraiyingyong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string AppBarDeleteBtnText {
            get {
                return ResourceManager.GetString("AppBarDeleteBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评分&amp;评价 的本地化字符串。
        /// </summary>
        public static string AppBarEvaluation {
            get {
                return ResourceManager.GetString("AppBarEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意见反馈 的本地化字符串。
        /// </summary>
        public static string AppBarFeedBack {
            get {
                return ResourceManager.GetString("AppBarFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的其他应用 的本地化字符串。
        /// </summary>
        public static string AppBarOtherApp {
            get {
                return ResourceManager.GetString("AppBarOtherApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看设置 的本地化字符串。
        /// </summary>
        public static string AppBarSettingBtnText {
            get {
                return ResourceManager.GetString("AppBarSettingBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string AppBarSureBtnText {
            get {
                return ResourceManager.GetString("AppBarSureBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏倒计时应用 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CancelMenuItem {
            get {
                return ResourceManager.GetString("CancelMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亲，请您重新选择一个将来的时间 的本地化字符串。
        /// </summary>
        public static string chooseDateTip {
            get {
                return ResourceManager.GetString("chooseDateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string CopyMenuItem {
            get {
                return ResourceManager.GetString("CopyMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要删除全部锁屏记事？ 的本地化字符串。
        /// </summary>
        public static string DeleteAllTip {
            get {
                return ResourceManager.GetString("DeleteAllTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteMenuItem {
            get {
                return ResourceManager.GetString("DeleteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要删除？ 的本地化字符串。
        /// </summary>
        public static string DeleteTip {
            get {
                return ResourceManager.GetString("DeleteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抱歉：程序闹情绪了...是否反馈给作者,帮您修理它？ 的本地化字符串。
        /// </summary>
        public static string ErrorTip {
            get {
                return ResourceManager.GetString("ErrorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再按一次退出 的本地化字符串。
        /// </summary>
        public static string ExitTip {
            get {
                return ResourceManager.GetString("ExitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ---------------------------------------
        ///Device Name：{0}
        ///Device Manufacturer：{1}
        ///Device Firmware Version：{2}
        ///Device Hardware Version：{3}
        ///--------------------------------------- 的本地化字符串。
        /// </summary>
        public static string FeedBackBody {
            get {
                return ResourceManager.GetString("FeedBackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. 点击[查看设置]按钮，弹出页面中点击[通知]一项的[选择一个应用以显示详细状态]项选择为[锁屏倒计时记事]，点击后退回到应用中 的本地化字符串。
        /// </summary>
        public static string FirstHelp {
            get {
                return ResourceManager.GetString("FirstHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5. 如果提示手机定期代理数量达到最大限制，请在手机的节电模式中将一些应用的 [允许应用在后台运行]选项设置为关闭 的本地化字符串。
        /// </summary>
        public static string FiveHelp {
            get {
                return ResourceManager.GetString("FiveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4. 如果提示无法开启倒计时提醒，请在手机的节电模式中打开[允许应用在后台运行]的选项 的本地化字符串。
        /// </summary>
        public static string FourHelp {
            get {
                return ResourceManager.GetString("FourHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}条历史记录 的本地化字符串。
        /// </summary>
        public static string HistoryCountTemplate {
            get {
                return ResourceManager.GetString("HistoryCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沒有任何历史记录 的本地化字符串。
        /// </summary>
        public static string HistoryEmptyTip {
            get {
                return ResourceManager.GetString("HistoryEmptyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示：请输入锁屏内容 的本地化字符串。
        /// </summary>
        public static string InputTip {
            get {
                return ResourceManager.GetString("InputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏显示内容 的本地化字符串。
        /// </summary>
        public static string lockScreenShowContent {
            get {
                return ResourceManager.GetString("lockScreenShowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距{0}还有{1}天 的本地化字符串。
        /// </summary>
        public static string LockTipTemplate {
            get {
                return ResourceManager.GetString("LockTipTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示 的本地化字符串。
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示：当前没有要清除的锁屏记事 的本地化字符串。
        /// </summary>
        public static string NoLockContentTip {
            get {
                return ResourceManager.GetString("NoLockContentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定到开始屏幕 的本地化字符串。
        /// </summary>
        public static string PinStartScreen {
            get {
                return ResourceManager.GetString("PinStartScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史记录 的本地化字符串。
        /// </summary>
        public static string PivotHelpHistory {
            get {
                return ResourceManager.GetString("PivotHelpHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用帮助 的本地化字符串。
        /// </summary>
        public static string PivotHelpItem {
            get {
                return ResourceManager.GetString("PivotHelpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string PivotIndexItem {
            get {
                return ResourceManager.GetString("PivotIndexItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示：锁屏记事清除成功 的本地化字符串。
        /// </summary>
        public static string RemoveSuccessTip {
            get {
                return ResourceManager.GetString("RemoveSuccessTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要删除当前提醒，{0} 的本地化字符串。
        /// </summary>
        public static string RemoveTip {
            get {
                return ResourceManager.GetString("RemoveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. 在输入框输入文字后点击[确定]按钮来设置锁屏文字；如果想清除锁屏文字，请点击[清除]按钮。 的本地化字符串。
        /// </summary>
        public static string SecondHelp {
            get {
                return ResourceManager.GetString("SecondHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏倒计时记事[{0}] 用户反馈 的本地化字符串。
        /// </summary>
        public static string SendFeedBack {
            get {
                return ResourceManager.GetString("SendFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设日期 的本地化字符串。
        /// </summary>
        public static string SetDate {
            get {
                return ResourceManager.GetString("SetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示：锁屏记事设置成功 的本地化字符串。
        /// </summary>
        public static string SetSuccessTip {
            get {
                return ResourceManager.GetString("SetSuccessTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还有 的本地化字符串。
        /// </summary>
        public static string StillDay {
            get {
                return ResourceManager.GetString("StillDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非常抱歉，本应用的后台计划已被禁用，无法开启倒计时提醒，请查看使用帮助。 的本地化字符串。
        /// </summary>
        public static string SystemErrorOne {
            get {
                return ResourceManager.GetString("SystemErrorOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非常抱歉，您的手机定期代理数量达到最大限制 的本地化字符串。
        /// </summary>
        public static string SystemErrorTwo {
            get {
                return ResourceManager.GetString("SystemErrorTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string TbDate {
            get {
                return ResourceManager.GetString("TbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3. 开启倒计时锁屏提醒，会在锁屏上显示天数倒数 的本地化字符串。
        /// </summary>
        public static string ThreeHelp {
            get {
                return ResourceManager.GetString("ThreeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启倒计时锁屏提醒 的本地化字符串。
        /// </summary>
        public static string ToggleSwithRemind {
            get {
                return ResourceManager.GetString("ToggleSwithRemind", resourceCulture);
            }
        }
    }
}
